### ISSUE TITLE
请教下，用UniverseNet训练的结果如何？

### ISSUE THREAD

**Issue by clw5180** [zhengye1995/Tianchi-2021-Guangdong-Tile-Detection#1]
我也遇到了损失是nan的问题，调大warmup_iters后虽然解决了，但是效果并不好；

**Comment by zhengye1995** [comment]
1. anchor box assign 在rpn用了atss，见https://github.com/zhengye1995/Tianchi-2021-Guangdong-Tile-Detection/blob/6ef9b0237d309d8ce55072747fc64e80c5c18568/configs/experiment/docker/cas_dcn_r50_temp.py#L104
2. UniverseNet50 在不加无目标图的情况下收敛的不错，效果比cas r50要好，但是加了无目标图需要调大warmup_iters，效果和你一样不行

**Comment by clw5180** [comment]
> 1. anchor box assign 在rpn用了atss，见https://github.com/zhengye1995/Tianchi-2021-Guangdong-Tile-Detection/blob/6ef9b0237d309d8ce55072747fc64e80c5c18568/configs/experiment/docker/cas_dcn_r50_temp.py#L104
> 2. UniverseNet50 在不加无目标图的情况下收敛的不错，效果比cas r50要好，但是加了无目标图需要调大warmup_iters，效果和你一样不行

感谢大佬，我刚测了下用 ATSSAssigner 替换 MaxIoUAssigner，涨点十分明显，不知道你那边大概能提高多少？

**Comment by zhengye1995** [comment]
> > 1. anchor box assign 在rpn用了atss，见https://github.com/zhengye1995/Tianchi-2021-Guangdong-Tile-Detection/blob/6ef9b0237d309d8ce55072747fc64e80c5c18568/configs/experiment/docker/cas_dcn_r50_temp.py#L104
> > 2. UniverseNet50 在不加无目标图的情况下收敛的不错，效果比cas r50要好，但是加了无目标图需要调大warmup_iters，效果和你一样不行
> 
> 感谢大佬，我刚测了下用 ATSSAssigner 替换 MaxIoUAssigner，涨点十分明显，不知道你那边大概能提高多少？

挺明显的，配合调anchor_scale 2个多点的AP
