### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.globalvar'

### ISSUE THREAD

**Issue by ouening** [zhengye1995/Tianchi-2021-Guangdong-Tile-Detection#10]
作者您好，推理过程执行python tools/inference_server_template.py   报错，也没在tools文件夹找到globalvar.py文件，请问怎么解决呢？

**Comment by zhengye1995** [comment]
请不要用这个代码推理，这个是针对天池平台的比赛测试用的，所以无法使用。
