### ISSUE TITLE
感谢分享，关于图片大小的请教

### ISSUE THREAD

**Issue by xilinniao123** [zhengye1995/Tianchi-2021-Guangdong-Tile-Detection#2]
您好：
感谢分享，这个比赛图片尺寸比较大（8K左右），我没有在您的代码里看到关于crop的信息，只是看到ResizeWithTemplate，请问您是否只是做了resize而没有做类似滑动窗口的切分？谢谢

**Comment by zhengye1995** [comment]
您好,开源的代码是round2 复赛的,复赛数据是小图,所以不需要切图

**Comment by xilinniao123** [comment]
感谢回复，请问阶段1切图您是如何处理的？

**Comment by zhengye1995** [comment]
处理方法是以下步骤：
1. 随机选择一个box作为基础框
2. 在这个box周围裁剪一个预设大小的patch，要求该box要被patch包围（box在patch上位置随机）
3. 进行其他box的合法性检查：如果落在patch内面积大于0.5倍原box面积的才合法（0.5是个阈值超参），落在外面的框不合法去掉
基本就是之前我参加天池宫颈癌异常细胞检测时的第二名的方案，可以去看一下当时的答辩视频
