### ISSUE TITLE
 img_scale问题以及batch size

### ISSUE THREAD

**Issue by JunjieLiuSWU** [zhengye1995/Tianchi-2021-Guangdong-Tile-Detection#3]
你好，我看配置文件里面设置img_scale=（10000, 1800），请问为什么长边要设为一万，我看数据集图片最长边只有两千左右，另外，请问batch size设为1对训练效果也影响不大吗

**Comment by zhengye1995** [comment]
关于图片大小：
1. 1800是短边尺寸，10000是长边的最大值，不是实际值。resize的时候是keep ratio也就是保持长宽比的，也就是短边1800，长边按照长宽比从1800的短边计算得出，10000只是限制了长边的上限。距离逻辑请看resize方法的实现
关于batch size：
首先目标检测任务的batch size本来就不大，因为显存问题，想大只能跨卡bn。在数据量较小的目标检测任务中，我个人惯用的方式是锁住bn，在这种情况下bn不更新，batch size大小就不怎么影响了，并且往往小batch效果反而更好，因为小的batch size相比大batch size同样的训练epoch训练迭代的次数可以多一些。（这个现象在之前我参加过的很多比赛中都验证过，比如8卡，每张卡2图，经常效果不如单卡单图好）
希望能够回答你的疑惑～

**Comment by JunjieLiuSWU** [comment]
感谢大佬的及时解答，学到很多。

**Comment by Haidong-Kang** [comment]
> 关于图片大小：
> 
> 1. 1800是短边尺寸，10000是长边的最大值，不是实际值。resize的时候是keep ratio也就是保持长宽比的，也就是短边1800，长边按照长宽比从1800的短边计算得出，10000只是限制了长边的上限。距离逻辑请看resize方法的实现
>    关于batch size：
>    首先目标检测任务的batch size本来就不大，因为显存问题，想大只能跨卡bn。在数据量较小的目标检测任务中，我个人惯用的方式是锁住bn，在这种情况下bn不更新，batch size大小就不怎么影响了，并且往往小batch效果反而更好，因为小的batch size相比大batch size同样的训练epoch训练迭代的次数可以多一些。（这个现象在之前我参加过的很多比赛中都验证过，比如8卡，每张卡2图，经常效果不如单卡单图好）
>    希望能够回答你的疑惑～

你好 问一下目标检测resize的设置问题 假设输入的img size<256，这个resize应该如何设置？短边的设置和图像输入尺寸有固定比例关系吗？谢谢

**Comment by zhengye1995** [comment]
> > 关于图片大小：
> > 
> > 1. 1800是短边尺寸，10000是长边的最大值，不是实际值。resize的时候是keep ratio也就是保持长宽比的，也就是短边1800，长边按照长宽比从1800的短边计算得出，10000只是限制了长边的上限。距离逻辑请看resize方法的实现
> >    关于batch size：
> >    首先目标检测任务的batch size本来就不大，因为显存问题，想大只能跨卡bn。在数据量较小的目标检测任务中，我个人惯用的方式是锁住bn，在这种情况下bn不更新，batch size大小就不怎么影响了，并且往往小batch效果反而更好，因为小的batch size相比大batch size同样的训练epoch训练迭代的次数可以多一些。（这个现象在之前我参加过的很多比赛中都验证过，比如8卡，每张卡2图，经常效果不如单卡单图好）
> >    希望能够回答你的疑惑～
> 
> 你好 问一下目标检测resize的设置问题 假设输入的img size<256，这个resize应该如何设置？短边的设置和图像输入尺寸有固定比例关系吗？谢谢

1. 训练尺度的设定不是单纯依赖 img size的，要综合考虑图像大小，目标 (bbox) 的大小，backbone的感受野，最终的目的就是能让小目标在最不济最浅的特征图上可以保持一定的特征大小，让大目标在最深的特征图上能被backbone感受野覆盖到，可以通过统计数据集的分布来计算得到一个理想的大小范围。此外由于显存的限制，可能你的尺度不可能无限大，这时候可能存在类似超大分辨率图片检测问题，要采用滑窗等处理手段。 总之这块还是要考虑很多方面的。
2.  关于长宽比的问题，大部分情况下习惯采用keep ratio即维持长宽比的设定，这样不会让图片resize变形。  

希望能帮到你
