### ISSUE TITLE
特征相减

### ISSUE THREAD

**Issue by raymond5891** [zhengye1995/Tianchi-2021-Guangdong-Tile-Detection#5]
你好，
大概看了下代码，主干网络出来的特征并没有像 README 里的 ppt 说的那样相减，而是直接 cat
实际代码和介绍有出入？

**Comment by zhengye1995** [comment]
你好，
有相减，cat在一起为了batch infer，相减逻辑在siameseFPN中,介绍的图上表示的也是FPN特征相减：
https://github.com/zhengye1995/Tianchi-2021-Guangdong-Tile-Detection/blob/6ef9b0237d309d8ce55072747fc64e80c5c18568/mmdet/models/necks/siamese_fpn.py#L225

**Comment by raymond5891** [comment]
学习了，多谢

**Comment by raymond5891** [comment]
PS: 果断 star
