### ISSUE TITLE
No module named 'tools.rearrange_weights'

### ISSUE THREAD

**Issue by ouening** [zhengye1995/Tianchi-2021-Guangdong-Tile-Detection#8]
在使用demo/image_demo.py程序进行推理的时候出现以下错误：
<pre>Traceback (most recent call last):
  File &quot;/Tianchi-2021-Guangdong-Tile-Detection-main/demo/image_demo.py&quot;, line 3, in &lt;module&gt;
    from mmdet.apis import inference_detector, init_detector, show_result_pyplot
  File &quot;/Tianchi-2021-Guangdong-Tile-Detection-main/mmdet/apis/__init__.py&quot;, line 4, in &lt;module&gt;
    from .train import get_root_logger, set_random_seed, train_detector
  File &quot;/Tianchi-2021-Guangdong-Tile-Detection-main/mmdet/apis/train.py&quot;, line 9, in &lt;module&gt;
    from tools.rearrange_weights import rearrange_classes
ModuleNotFoundError: No module named &apos;tools.rearrange_weights&apos;
</pre>

**Comment by ouening** [comment]
还有能否提供预训练权重呢?按照作者的配置在2080显卡训练不了，降低图片尺度训练后使用tools/test.py进行eval的结果很差

**Comment by zhengye1995** [comment]
> 在使用demo/image_demo.py程序进行推理的时候出现以下错误：
> 
> Traceback (most recent call last):
>   File "/Tianchi-2021-Guangdong-Tile-Detection-main/demo/image_demo.py", line 3, in <module>
>     from mmdet.apis import inference_detector, init_detector, show_result_pyplot
>   File "/Tianchi-2021-Guangdong-Tile-Detection-main/mmdet/apis/__init__.py", line 4, in <module>
>     from .train import get_root_logger, set_random_seed, train_detector
>   File "/Tianchi-2021-Guangdong-Tile-Detection-main/mmdet/apis/train.py", line 9, in <module>
>     from tools.rearrange_weights import rearrange_classes
> ModuleNotFoundError: No module named 'tools.rearrange_weights'

你是在哪个路径下执行的 python demo/image_demo.py 呢，可能是因为目录原因找不到包，实际是有的，这个是python常见问题

**Comment by zhengye1995** [comment]
> 还有能否提供预训练权重呢?按照作者的配置在2080显卡训练不了，降低图片尺度训练后使用tools/test.py进行eval的结果很差

不知道你是用的初赛还是复赛的数据集，初赛的图像比复赛大很多，复赛是crop出来的，我的代码是针对复赛的。

预训练模型的话得等我开学回了学校发了，模型应该在实验室的电脑里面，抱歉。

**Comment by ouening** [comment]
我是用您config文件中提到的round2的两组数据进行训练的，是复赛的数据。那到时麻烦发一下预训练模型哈

**Comment by jaffe-fly** [comment]
权重有发出来嘛？
