### ISSUE TITLE
tools/test.py执行后中文标签乱码问题

### ISSUE THREAD

**Issue by ouening** [zhengye1995/Tianchi-2021-Guangdong-Tile-Detection#9]
tools/test.py使用--show-dir参数后保存检测的图像，发现标签乱码，如下图：
![image](https://user-images.githubusercontent.com/15122811/151003031-43da17ad-7f0c-4850-80d5-861350b9485e.png)

请问作者该如何解决呢？

**Comment by zhengye1995** [comment]
因为 mmdet默认可视化基于mmcv，后端实际上是基于opencv的，中文没有字体的确是乱码的，建议使用英文类别名称。

把[这里](https://github.com/zhengye1995/Tianchi-2021-Guangdong-Tile-Detection/blob/4ef61bfa472296a4ccfe525b88fd8e40b0b99524/mmdet/datasets/ceramic.py#L31)的代码中的名字改成英文的，原始的是中文的

**Comment by ouening** [comment]
在mmdet/models/detectors/base_template.py中的第333行class_names设为None就可以显示数字标签了
